export const environment = {
  production: true,
  getAllRunsUrl: 'http://localhost:3001/allRuns',
  getAllPbsUrl: 'http://localhost:3001/allPbs',
  editPbUrl: 'http://localhost:3001/editPb',
  getSpecificRunsUrl: 'http://localhost:3001/specificRuns',
  logNewRunUrl: 'http://localhost:3001/logRun',
  editRunUrl: 'http://localhost:3001/editRun',
  deleteRunUrl: 'http://localhost:3001/deleteRun',
  getDaysOfWeekDistanceUrl: 'http://localhost:3001/dayOfWeekDistance',
  getTotalMilesForMonthInYear: 'http://localhost:3001/totalForMonthYear',
  averageDistancePerDayMonthYear: 'http://localhost:3001/dailyAvgForMonthYear',
  totalDistanceRan: 'http://localhost:3001/totalDistance',
  longestRun: 'http://localhost:3001/longestRun',
  currentWeekTotal: 'http://localhost:3001/currentWeekTotal',
  totalLast6Months: 'http://localhost:3001/last6MonthsTotal',
  imageUploadUrl: 'http://localhost:3001/api/upload',
  addImgToDbUrl: 'http://localhost:3001/addImageToDb',
  getAllShoesUrl: 'http://localhost:3001/allShoes',
  addNewShoesUrl: 'http://localhost:3001/addShoe',
  increaseShoeMileageUrl: 'http://localhost:3001/increaseShoeDistance',
  decreaseShoeMileageUrl: 'http://localhost:3001/decreaseShoeDistance',
  retireShoeUrl: 'http://localhost:3001/retire',
  reactivateShoeUrl: 'http://localhost:3001/reactivate',
  deleteShoeUrl: 'http://localhost:3001/deleteShoe',
};
