export const environment = {
  production: true,
  getAllRunsUrl: 'http://localhost:3001/allRuns',
  getSpecificRunsUrl: 'http://localhost:3001/specificRuns',
  logNewRunUrl: 'http://localhost:3001/logRun',
  editRunUrl: 'http://localhost:3001/editRun',
  deleteRunUrl: 'http://localhost:3001/deleteRun',
  getDaysOfWeekDistanceUrl: 'http://localhost:3001/dayOfWeekDistance',
  getTotalMilesForMonthInYear: 'http://localhost:3001/totalForMonthYear',
  averageDistancePerDayMonthYear: 'http://localhost:3001/dailyAvgForMonthYear',
  totalDistanceRan: 'http://localhost:3001/totalDistance',
  longestRun: 'http://localhost:3001/longestRun',
  currentWeekTotal: 'http://localhost:3001/currentWeekTotal',
  totalLast6Months: 'http://localhost:3001/last6MonthsTotal',
};
